Repository AR-TTUBEOG/Back-Spring, pull requests merged in 2024-01, with the labels that each got.

#4 [Feat] Benefit 생성, 수정, 삭제 API
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/domain/Benefit.java
  src/main/java/com/ttubeog/domain/benefit/domain/BenefitType.java
  src/main/java/com/ttubeog/domain/benefit/dto/request/CreateBenefitReq.java
  src/main/java/com/ttubeog/domain/benefit/dto/request/UpdateBenefitReq.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/CreateBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/UpdateBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
Labels: 🚶‍♀️초은, ✨ feature

#7 [Feat] Comment 작성, 수정, 삭제 구현
  src/main/java/com/ttubeog/domain/comment/application/CommentService.java
  src/main/java/com/ttubeog/domain/comment/domain/Comment.java
  src/main/java/com/ttubeog/domain/comment/dto/request/UpdateCommentReq.java
  src/main/java/com/ttubeog/domain/comment/dto/request/WriteCommentReq.java
  src/main/java/com/ttubeog/domain/comment/dto/response/UpdateCommentRes.java
  src/main/java/com/ttubeog/domain/comment/dto/response/WriteCommentRes.java
  src/main/java/com/ttubeog/domain/comment/presentation/CommentController.java
Labels: 🚶‍♀️정민, ✨ feature

#6 [Feat] 카카오 로그인 초기 세팅
  build.gradle
  src/main/java/com/ttubeog/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/ttubeog/domain/auth/application/CustomMemberDetailsService.java
  src/main/java/com/ttubeog/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/ttubeog/domain/auth/application/JwtTokenService.java
  src/main/java/com/ttubeog/domain/auth/application/KakaoOauthService.java
  src/main/java/com/ttubeog/domain/auth/application/OauthService.java
  src/main/java/com/ttubeog/domain/auth/config/SecurityDomainConfig.java
  src/main/java/com/ttubeog/domain/auth/controller/OauthController.java
  src/main/java/com/ttubeog/domain/auth/dto/KakaoInfoDto.java
  src/main/java/com/ttubeog/domain/auth/dto/OauthRequestDto.java
  src/main/java/com/ttubeog/domain/auth/dto/OauthResponseDto.java
  src/main/java/com/ttubeog/domain/auth/dto/RefreshTokenResponseDto.java
  src/main/java/com/ttubeog/domain/auth/filter/JwtFilter.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/Provider.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/dto/MemberDto.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/global/config/security/SecurityConfig.java
  src/main/java/com/ttubeog/global/config/security/auth/OAuth2UserInfo.java
  src/main/java/com/ttubeog/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/ttubeog/global/config/security/auth/company/Kakao.java
Labels: 🚶‍♀️아린, ✨ feature

#10 [Chore] Discord log back
  .gitignore
  build.gradle
Labels: 🚶‍♂️상제, ✨ feature

#12 [Feat] Benefit 조회, 사용, 저장 구현
  src/main/java/com/ttubeog/TtubeogApplication.java
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/domain/MemberBenefit.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/MemberBenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/SaveBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/exception/AlreadyUsedBenefitException.java
  src/main/java/com/ttubeog/domain/benefit/exception/InvalidMemberBenefitException.java
  src/main/java/com/ttubeog/domain/benefit/exception/NonExistentBenefitException.java
  src/main/java/com/ttubeog/domain/benefit/exception/OverlappingBenefitException.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
  src/main/java/com/ttubeog/domain/common/BaseEntity.java
Labels: 🚶‍♀️초은, ✨ feature

#11 [Feat] 카카오 로그인 구체화
  build.gradle
  src/main/java/com/ttubeog/domain/auth/application/CustomDefaultOAuth2UserService.java
  src/main/java/com/ttubeog/domain/auth/application/CustomMemberDetailsService.java
  src/main/java/com/ttubeog/domain/auth/application/CustomTokenProviderService.java
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
  src/main/java/com/ttubeog/domain/auth/controller/OauthController.java
  src/main/java/com/ttubeog/domain/auth/filter/JwtFilter.java
  src/main/java/com/ttubeog/domain/auth/service/JwtTokenService.java
  src/main/java/com/ttubeog/domain/auth/service/KakaoOauthService.java
  src/main/java/com/ttubeog/domain/auth/service/OauthService.java
  src/main/java/com/ttubeog/domain/auth/utils/SecurityUtil.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/MemberRole.java
  src/main/java/com/ttubeog/domain/member/dto/MemberDto.java
  src/main/java/com/ttubeog/domain/member/mapper/MemberMapper.java
  src/main/java/com/ttubeog/global/config/security/SecurityConfig.java
  src/main/java/com/ttubeog/global/config/security/auth/OAuth2UserInfoFactory.java
  src/main/java/com/ttubeog/global/config/security/auth/company/Kakao.java
  src/main/java/com/ttubeog/global/config/security/handler/CustomSimpleUrlAuthenticationSuccessHandler.java
  src/main/java/com/ttubeog/global/config/security/token/CustomOncePerRequestFilter.java
  src/main/java/com/ttubeog/global/config/security/token/UserPrincipal.java
Labels: 🚶‍♀️아린, ✨ feature

#15 [Hotfix] 스웨거 JWT 예외 해결
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
  src/main/java/com/ttubeog/domain/auth/controller/OauthController.java
  src/main/java/com/ttubeog/domain/auth/exception/CustomException.java
  src/main/java/com/ttubeog/domain/auth/exception/ErrorCode.java
  src/main/java/com/ttubeog/domain/auth/exception/ErrorResponse.java
  src/main/java/com/ttubeog/domain/auth/exception/ExceptionHandlerFilter.java
  src/main/java/com/ttubeog/domain/auth/exception/GlobalExceptionHandler.java
  src/main/java/com/ttubeog/domain/auth/filter/JwtFilter.java
  src/main/java/com/ttubeog/domain/auth/service/OauthService.java
  src/main/java/com/ttubeog/global/config/SwaggerConfig.java
Labels: 🚶‍♀️초은, 🚶‍♀️정민, 🚶‍♂️상제, 🚶‍♀️아린, ✨ feature, 🔥 bug

#22 [Fix] : Swagger 정상화
  .gitignore
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
Labels: 🔥 bug

#23 [Feat] 애플 로그인 API 구현
  build.gradle
  src/main/java/com/ttubeog/domain/auth/config/FeignClientConfig.java
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
  src/main/java/com/ttubeog/domain/auth/controller/OauthController.java
  src/main/java/com/ttubeog/domain/auth/domain/Token.java
  src/main/java/com/ttubeog/domain/auth/domain/repository/CustomAuthorizationRequestRepository.java
  src/main/java/com/ttubeog/domain/auth/domain/repository/TokenRepository.java
  src/main/java/com/ttubeog/domain/auth/dto/OAuthPlatformMemberResponse.java
  src/main/java/com/ttubeog/domain/auth/dto/OauthResponseDto.java
  src/main/java/com/ttubeog/domain/auth/dto/TokenMapping.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/AppleAuthRequest.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/AppleEventResponse.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/AppleLoginRequest.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/ApplePublicKey.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/ApplePublicKeyResponse.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/AppleUser.java
  src/main/java/com/ttubeog/domain/auth/dto/apple/Name.java
  src/main/java/com/ttubeog/domain/auth/dto/kakao/KakaoInfoDto.java
  src/main/java/com/ttubeog/domain/auth/exception/ErrorCode.java
  src/main/java/com/ttubeog/domain/auth/feign/AppleAuthClient.java
  src/main/java/com/ttubeog/domain/auth/filter/JwtFilter.java
  src/main/java/com/ttubeog/domain/auth/service/AppleOAtuhUserProvider.java
  src/main/java/com/ttubeog/domain/auth/service/JwtTokenService.java
  src/main/java/com/ttubeog/domain/auth/service/KakaoOauthService.java
  src/main/java/com/ttubeog/domain/auth/service/OauthService.java
  src/main/java/com/ttubeog/domain/auth/service/PublicKeyGenerator.java
  src/main/java/com/ttubeog/domain/auth/utils/AppleClaimsValidator.java
  src/main/java/com/ttubeog/domain/auth/utils/AppleJwtParser.java
  src/main/java/com/ttubeog/domain/auth/utils/EncryptUtils.java
  src/main/java/com/ttubeog/domain/auth/utils/SecurityUtil.java
  src/main/java/com/ttubeog/domain/member/dto/MemberDto.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/global/config/security/handler/CustomSimpleUrlAuthenticationFailureHandler.java
Labels: 🚶‍♀️아린, ✨ feature

#24 [Hotfix] add logback.xml to git secret key
  .github/workflows/gradle.yml
Labels: 🚶‍♂️상제, 🔥 bug
