Repository AR-TTUBEOG/Back-Spring, pull requests merged in 2024-03, with the labels that each got.

#95 [Hotfix] spot Controller findBySpotId API endpoint 수정
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
Labels: 🔥 bug

#92 [Refactor] 전체 파일 응답 호출방법 수정
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
  src/main/java/com/ttubeog/domain/comment/application/CommentService.java
  src/main/java/com/ttubeog/domain/comment/presentation/CommentController.java
  src/main/java/com/ttubeog/domain/game/application/GameService.java
  src/main/java/com/ttubeog/domain/game/presentation/GameController.java
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/presentation/GuestBookController.java
  src/main/java/com/ttubeog/domain/image/application/ImageService.java
  src/main/java/com/ttubeog/domain/image/presentation/ImageController.java
  src/main/java/com/ttubeog/domain/likes/application/LikesService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/domain/place/application/PlaceService.java
  src/main/java/com/ttubeog/domain/place/presentation/PlaceController.java
  src/main/java/com/ttubeog/domain/road/application/RoadService.java
  src/main/java/com/ttubeog/domain/road/presentation/RoadController.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/presentation/StoreController.java
  src/main/java/com/ttubeog/global/error/ApiControllerAdvice.java
  src/main/java/com/ttubeog/global/payload/CommonDto.java
Labels: 🚶‍♀️초은, ⚒️ refactor

#97 [Fix] ImageController Endpoint 에러 수정
  src/main/java/com/ttubeog/domain/image/presentation/ImageController.java
Labels: 🚶‍♀️초은, 🔥 bug

#90 [Refactor] SpringDoc 수정
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
Labels: 🚶‍♀️정민, ⚒️ refactor
