Repository AR-TTUBEOG/Back-Spring, pull requests merged in 2024-02, with the labels that each got.

#31 [REFACTOR] 카카오 로그인 리팩토링
  src/main/java/com/ttubeog/domain/auth/controller/AuthController.java
  src/main/java/com/ttubeog/domain/auth/dto/KakaoInfoDto.java
  src/main/java/com/ttubeog/domain/auth/dto/request/KakaoLoginRequest.java
  src/main/java/com/ttubeog/domain/auth/dto/response/KakaoTokenResponse.java
  src/main/java/com/ttubeog/domain/auth/security/JwtTokenProvider.java
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
Labels: 🚶‍♀️아린, ✨ feature, ⚒️ refactor

#36 [FEAT] 소셜 로그인 JWT 토큰으로 현재 유저 조회
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
  src/main/java/com/ttubeog/domain/auth/config/SecurityUtil.java
  src/main/java/com/ttubeog/domain/auth/security/JwtTokenProvider.java
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/MemberRole.java
  src/main/java/com/ttubeog/domain/member/domain/Provider.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberDetailRes.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/global/config/security/token/UserPrincipal.java
Labels: 🚶‍♀️아린, ✨ feature

#38 [FEAT] 소셜 로그인 멤버 회원가입 API
  src/main/java/com/ttubeog/domain/auth/config/SecurityUtil.java
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/dto/MemberDto.java
  src/main/java/com/ttubeog/domain/member/dto/request/ProduceNicknameRequest.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberDetailRes.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/global/config/security/token/UserPrincipal.java
Labels: 🚶‍♀️아린, ✨ feature

#40 [Feat]: 게임 관련 api
  build.gradle
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/domain/Benefit.java
  src/main/java/com/ttubeog/domain/benefit/domain/MemberBenefit.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/MemberBenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
  src/main/java/com/ttubeog/domain/game/application/GameService.java
  src/main/java/com/ttubeog/domain/game/domain/BasketballGame.java
  src/main/java/com/ttubeog/domain/game/domain/Game.java
  src/main/java/com/ttubeog/domain/game/domain/GameType.java
  src/main/java/com/ttubeog/domain/game/domain/GiftGame.java
  src/main/java/com/ttubeog/domain/game/domain/RouletteGame.java
  src/main/java/com/ttubeog/domain/game/domain/RouletteOption.java
  src/main/java/com/ttubeog/domain/game/domain/repository/BasketBallRepository.java
  src/main/java/com/ttubeog/domain/game/domain/repository/GameRepository.java
  src/main/java/com/ttubeog/domain/game/domain/repository/GiftGameRepository.java
  src/main/java/com/ttubeog/domain/game/domain/repository/RouletteRepository.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateRouletteReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateRouletteReq.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/FindGameRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/exception/NonExistentGameException.java
  src/main/java/com/ttubeog/domain/game/exception/OverlappingGameException.java
  src/main/java/com/ttubeog/domain/game/presentation/GameController.java
Labels: 🚶‍♀️초은, ✨ feature

#41 [FEAT] 토큰 재발급 API 구현
  src/main/java/com/ttubeog/domain/auth/controller/AuthController.java
  src/main/java/com/ttubeog/domain/auth/security/JwtTokenProvider.java
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/exception/InvalidAccessTokenExpiredException.java
  src/main/java/com/ttubeog/domain/member/exception/InvalidMemberException.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/global/config/security/token/UserPrincipal.java
Labels: 🚶‍♀️아린, ✨ feature

#46 [Feat] spot domain 구현 ( Feature/17 -> dev )
  src/main/java/com/ttubeog/domain/area/domain/DongArea.java
  src/main/java/com/ttubeog/domain/auth/config/SecurityConfig.java
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/dto/CreateGuestBookRequestDto.java
  src/main/java/com/ttubeog/domain/image/application/ImageService.java
  src/main/java/com/ttubeog/domain/image/domain/Image.java
  src/main/java/com/ttubeog/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/ttubeog/domain/image/dto/request/CreateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/request/ImageRequestType.java
  src/main/java/com/ttubeog/domain/image/dto/request/UpdateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/ttubeog/domain/image/exception/InvalidImageException.java
  src/main/java/com/ttubeog/domain/member/exception/InvalidMemberException.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/domain/Spot.java
  src/main/java/com/ttubeog/domain/spot/domain/repository/SpotRepository.java
  src/main/java/com/ttubeog/domain/spot/dto/request/CreateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/request/UpdateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/response/SpotResponseDto.java
  src/main/java/com/ttubeog/domain/spot/exception/AlreadyExistsSpotException.java
  src/main/java/com/ttubeog/domain/spot/exception/InvalidDongAreaException.java
  src/main/java/com/ttubeog/domain/spot/exception/InvalidImageListSizeException.java
  src/main/java/com/ttubeog/domain/spot/exception/InvalidSpotIdException.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
  src/main/java/com/ttubeog/domain/store/domain/Store.java
Labels: ✨ feature

#49 [FEAT] 로그아웃 API 구현
  src/main/java/com/ttubeog/domain/auth/security/JwtTokenProvider.java
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberDetailRes.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
Labels: 🚶‍♀️아린, ✨ feature

#51 [Feat] Image 구현
  src/main/java/com/ttubeog/domain/guestbook/domain/GuestBook.java
  src/main/java/com/ttubeog/domain/guestbook/exception/InvalidGuestBookIdException.java
  src/main/java/com/ttubeog/domain/image/application/ImageService.java
  src/main/java/com/ttubeog/domain/image/domain/Image.java
  src/main/java/com/ttubeog/domain/image/domain/ImageType.java
  src/main/java/com/ttubeog/domain/image/dto/request/CreateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/request/ImageRequestType.java
  src/main/java/com/ttubeog/domain/image/dto/request/UpdateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/ttubeog/domain/image/exception/InvalidImageTypeException.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
Labels: 🚶‍♂️상제, ✨ feature

#48 [Chore] Comment 현재 유저 조회 방식 수정
  src/main/java/com/ttubeog/domain/comment/application/CommentService.java
  src/main/java/com/ttubeog/domain/comment/dto/request/GetCommentReq.java
  src/main/java/com/ttubeog/domain/comment/dto/response/GetCommentRes.java
  src/main/java/com/ttubeog/domain/comment/exception/NonExistentCommentException.java
  src/main/java/com/ttubeog/domain/comment/exception/UnauthorizedMemberException.java
  src/main/java/com/ttubeog/domain/comment/presentation/CommentController.java
Labels: 🚶‍♀️정민, ⚒️ refactor

#52 [Chore] Benefit-Game 관계 변경
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/domain/Benefit.java
  src/main/java/com/ttubeog/domain/benefit/domain/BenefitType.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/BenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/MemberBenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/dto/request/CreateBenefitReq.java
  src/main/java/com/ttubeog/domain/benefit/dto/request/UpdateBenefitReq.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/CreateBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/SaveBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/UpdateBenefitRes.java
  src/main/java/com/ttubeog/domain/benefit/presentation/BenefitController.java
  src/main/java/com/ttubeog/domain/game/application/GameService.java
  src/main/java/com/ttubeog/domain/game/domain/Game.java
  src/main/java/com/ttubeog/domain/game/domain/RouletteGame.java
  src/main/java/com/ttubeog/domain/game/domain/repository/GameRepository.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateRouletteReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateRouletteReq.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/FindGameRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/RouletteBenefitResDto.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/exception/OverlappingGameException.java
  src/main/java/com/ttubeog/domain/game/presentation/GameController.java
Labels: 🚶‍♀️초은, ⚒️ refactor

#53 [Feat] Store 도메인 구현
  src/main/java/com/ttubeog/domain/area/domain/DongArea.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/BenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/MemberBenefitRepository.java
  src/main/java/com/ttubeog/domain/guestbook/domain/GuestBook.java
  src/main/java/com/ttubeog/domain/guestbook/domain/repository/GuestBookRepository.java
  src/main/java/com/ttubeog/domain/image/application/ImageService.java
  src/main/java/com/ttubeog/domain/likes/domain/Likes.java
  src/main/java/com/ttubeog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/domain/Store.java
  src/main/java/com/ttubeog/domain/store/domain/StoreType.java
  src/main/java/com/ttubeog/domain/store/dto/request/RegisterStoreReq.java
  src/main/java/com/ttubeog/domain/store/dto/request/UpdateStoreReq.java
  src/main/java/com/ttubeog/domain/store/dto/response/GetStoreDetailRes.java
  src/main/java/com/ttubeog/domain/store/dto/response/RegisterStoreRes.java
  src/main/java/com/ttubeog/domain/store/dto/response/UpdateStoreRes.java
  src/main/java/com/ttubeog/domain/store/exception/InvalidDongAreaException.java
  src/main/java/com/ttubeog/domain/store/exception/InvalidStoreIdException.java
  src/main/java/com/ttubeog/domain/store/exception/NonExistentStoreException.java
  src/main/java/com/ttubeog/domain/store/exception/UnathorizedMemberException.java
  src/main/java/com/ttubeog/domain/store/presentation/StoreController.java
Labels: 🚶‍♀️정민, ✨ feature

#58 [Feat] Likes 도메인 구현
  src/main/java/com/ttubeog/domain/likes/application/LikesService.java
  src/main/java/com/ttubeog/domain/likes/domain/Likes.java
  src/main/java/com/ttubeog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/com/ttubeog/domain/likes/exception/AlreadyLikesException.java
  src/main/java/com/ttubeog/domain/likes/presentation/LikesController.java
  src/main/java/com/ttubeog/domain/spot/exception/NonExistentSpotException.java
  src/main/java/com/ttubeog/domain/store/presentation/StoreController.java
Labels: 🚶‍♀️정민, ✨ feature

#55 [Feat] 회원탈퇴 API 구현
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/exception/FailureMemberDeleteException.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
Labels: 🚶‍♀️아린, ✨ feature

#61 [Feat] GuestBook domain 구현 및 적용
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/domain/GuestBook.java
  src/main/java/com/ttubeog/domain/guestbook/domain/GuestBookType.java
  src/main/java/com/ttubeog/domain/guestbook/domain/repository/GuestBookRepository.java
  src/main/java/com/ttubeog/domain/guestbook/dto/CreateGuestBookRequestDto.java
  src/main/java/com/ttubeog/domain/guestbook/dto/request/CreateGuestBookRequestDto.java
  src/main/java/com/ttubeog/domain/guestbook/dto/request/UpdateGuestBookRequestDto.java
  src/main/java/com/ttubeog/domain/guestbook/dto/response/GuestBookResponseDto.java
  src/main/java/com/ttubeog/domain/guestbook/exception/InvalidGuestBookException.java
  src/main/java/com/ttubeog/domain/guestbook/presentation/GuestBookController.java
  src/main/java/com/ttubeog/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/ttubeog/domain/member/exception/InvalidRegisterMemberException.java
  src/main/java/com/ttubeog/domain/road/application/RoadService.java
  src/main/java/com/ttubeog/domain/road/domain/Road.java
  src/main/java/com/ttubeog/domain/road/domain/RoadType.java
  src/main/java/com/ttubeog/domain/road/dto/request/CreateRoadRequestDto.java
  src/main/java/com/ttubeog/domain/road/dto/response/RoadResponseDto.java
  src/main/java/com/ttubeog/domain/road/exception/InvalidRoadIdException.java
  src/main/java/com/ttubeog/domain/road/exception/InvalidRoadTypeException.java
  src/main/java/com/ttubeog/domain/road/exception/NullRoadCoordinateException.java
  src/main/java/com/ttubeog/domain/road/presentation/RoadController.java
  src/main/java/com/ttubeog/domain/roadcoordinate/application/RoadCoordinateService.java
  src/main/java/com/ttubeog/domain/roadcoordinate/domain/RoadCoordinate.java
  src/main/java/com/ttubeog/domain/roadcoordinate/domain/repository/RoadCoordinateRepository.java
  src/main/java/com/ttubeog/domain/roadcoordinate/dto/request/CreateRoadCoordinateRequestDto.java
  src/main/java/com/ttubeog/domain/roadcoordinate/dto/response/RoadResponseCoordinateDto.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
Labels: 🚶‍♂️상제, ✨ feature

#65 [Feat] Road Domain(산책로) 구현
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/domain/GuestBook.java
  src/main/java/com/ttubeog/domain/guestbook/domain/repository/GuestBookRepository.java
  src/main/java/com/ttubeog/domain/guestbook/dto/response/GuestBookResponseDto.java
  src/main/java/com/ttubeog/domain/guestbook/presentation/GuestBookController.java
  src/main/java/com/ttubeog/domain/road/application/RoadService.java
  src/main/java/com/ttubeog/domain/road/domain/Road.java
  src/main/java/com/ttubeog/domain/road/domain/RoadType.java
  src/main/java/com/ttubeog/domain/road/domain/repository/RoadRepository.java
  src/main/java/com/ttubeog/domain/road/dto/request/CreateRoadRequestDto.java
  src/main/java/com/ttubeog/domain/road/dto/response/RoadResponseDto.java
  src/main/java/com/ttubeog/domain/road/exception/DuplicateRoadNameException.java
  src/main/java/com/ttubeog/domain/road/exception/InvalidRoadIdException.java
  src/main/java/com/ttubeog/domain/road/presentation/RoadController.java
  src/main/java/com/ttubeog/domain/roadcoordinate/application/RoadCoordinateService.java
  src/main/java/com/ttubeog/domain/roadcoordinate/domain/RoadCoordinate.java
  src/main/java/com/ttubeog/domain/roadcoordinate/domain/repository/RoadCoordinateRepository.java
  src/main/java/com/ttubeog/domain/roadcoordinate/dto/request/CreateRoadCoordinateRequestDto.java
  src/main/java/com/ttubeog/domain/roadcoordinate/dto/response/RoadResponseCoordinateDto.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
Labels: 🚶‍♂️상제, ✨ feature

#64 [Feat] Store, Benefit 연결
  src/main/java/com/ttubeog/domain/benefit/application/BenefitService.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/BenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/domain/repository/MemberBenefitRepository.java
  src/main/java/com/ttubeog/domain/benefit/dto/response/SaveBenefitRes.java
  src/main/java/com/ttubeog/domain/game/application/GameService.java
  src/main/java/com/ttubeog/domain/game/domain/repository/GameRepository.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/CreateRouletteReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateBasketballReq.java
  src/main/java/com/ttubeog/domain/game/dto/request/UpdateGiftReq.java
  src/main/java/com/ttubeog/domain/game/dto/response/BenefitResDto.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/CreateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/FindGameRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateBasketballRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateGiftRes.java
  src/main/java/com/ttubeog/domain/game/dto/response/UpdateRouletteRes.java
  src/main/java/com/ttubeog/domain/game/exception/AlreadyExistGameException.java
  src/main/java/com/ttubeog/domain/game/presentation/GameController.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/domain/repository/StoreRepository.java
  src/main/java/com/ttubeog/domain/store/exception/InvalidStoreIdException.java
  src/main/java/com/ttubeog/domain/store/presentation/StoreController.java
Labels: 🚶‍♀️초은, ⚒️ refactor

#66 [Fix] 닉네임 설정 500에러 수정
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberNicknameRes.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
Labels: 🚶‍♀️아린, ✨ feature

#67 [Feat] Place 도메인 구현
  src/main/java/com/ttubeog/domain/area/domain/DongArea.java
  src/main/java/com/ttubeog/domain/likes/application/LikesService.java
  src/main/java/com/ttubeog/domain/likes/domain/repository/LikesRepository.java
  src/main/java/com/ttubeog/domain/place/application/PlaceService.java
  src/main/java/com/ttubeog/domain/place/domain/PlaceType.java
  src/main/java/com/ttubeog/domain/place/dto/request/GetNearbyPlaceReq.java
  src/main/java/com/ttubeog/domain/place/dto/request/SearchPlaceReq.java
  src/main/java/com/ttubeog/domain/place/dto/response/GetAllPlaceRes.java
  src/main/java/com/ttubeog/domain/place/dto/response/SearchPlaceRes.java
  src/main/java/com/ttubeog/domain/place/presentation/PlaceController.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
Labels: 🚶‍♀️정민, ✨ feature

#70 [Update] : Spot/Store Entity dongArea colmn 타입 String 변경
  src/main/java/com/ttubeog/domain/place/application/PlaceService.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/domain/Spot.java
  src/main/java/com/ttubeog/domain/spot/dto/request/CreateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/request/UpdateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/response/SpotResponseDto.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/domain/Store.java
  src/main/java/com/ttubeog/domain/store/dto/request/RegisterStoreReq.java
  src/main/java/com/ttubeog/domain/store/dto/response/GetStoreDetailRes.java
  src/main/java/com/ttubeog/domain/store/dto/response/RegisterStoreRes.java
Labels: 🚶‍♂️상제, 🔧 update

#72 [Fix] 페이징 예외 수정
  src/main/java/com/ttubeog/domain/place/application/PlaceService.java
Labels: 🚶‍♀️정민, 🔥 bug

#71 [Feat] 내 산책로, 매장 조회 API 구현
  src/main/java/com/ttubeog/domain/auth/service/AuthService.java
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/domain/Member.java
  src/main/java/com/ttubeog/domain/member/domain/repository/MemberRepository.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberDetailDto.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberNicknameDto.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberPlaceDto.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
Labels: 🚶‍♀️아린, ✨ feature

#78 [Feat] 방명록, 스팟 프론트요구사항 반영
  src/main/java/com/ttubeog/domain/comment/application/CommentService.java
  src/main/java/com/ttubeog/domain/comment/domain/Comment.java
  src/main/java/com/ttubeog/domain/comment/dto/request/GetCommentReq.java
  src/main/java/com/ttubeog/domain/comment/dto/request/WriteCommentReq.java
  src/main/java/com/ttubeog/domain/comment/dto/response/WriteCommentRes.java
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/dto/response/GuestBookResponseDto.java
  src/main/java/com/ttubeog/domain/place/application/PlaceService.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/domain/Spot.java
  src/main/java/com/ttubeog/domain/spot/dto/request/CreateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/request/UpdateSpotRequestDto.java
  src/main/java/com/ttubeog/domain/spot/dto/response/GetSpotDetailRes.java
  src/main/java/com/ttubeog/domain/spot/dto/response/SpotResponseDto.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
Labels: 🚶‍♀️초은, ⚒️ refactor

#79 [Feature] 이미지 멀티파트폼 구현
  build.gradle
  src/main/java/com/ttubeog/domain/UuidImage/domain/UuidImage.java
  src/main/java/com/ttubeog/domain/UuidImage/domain/repository/UuidImageRepository.java
  src/main/java/com/ttubeog/domain/aws/s3/AmazonS3Manager.java
  src/main/java/com/ttubeog/domain/aws/s3/S3PhotoService.java
  src/main/java/com/ttubeog/domain/guestbook/application/GuestBookService.java
  src/main/java/com/ttubeog/domain/guestbook/dto/request/CreateGuestBookRequestDto.java
  src/main/java/com/ttubeog/domain/guestbook/presentation/GuestBookController.java
  src/main/java/com/ttubeog/domain/image/application/ImageService.java
  src/main/java/com/ttubeog/domain/image/domain/Image.java
  src/main/java/com/ttubeog/domain/image/domain/ImageType.java
  src/main/java/com/ttubeog/domain/image/domain/repository/ImageRepository.java
  src/main/java/com/ttubeog/domain/image/dto/request/CreateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/request/UpdateImageRequestDto.java
  src/main/java/com/ttubeog/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/ttubeog/domain/image/exception/InvalidImageException.java
  src/main/java/com/ttubeog/domain/image/exception/InvalidImageTypeException.java
  src/main/java/com/ttubeog/domain/image/presentation/ImageController.java
  src/main/java/com/ttubeog/domain/spot/application/SpotService.java
  src/main/java/com/ttubeog/domain/spot/dto/response/SpotResponseDto.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/dto/response/GetStoreDetailRes.java
  src/main/java/com/ttubeog/global/config/AmazonConfig.java
Labels: 🚶‍♂️상제, ✨ feature

#81 [Feat] 스웨거 빠진 부분 보충
  src/main/java/com/ttubeog/domain/image/dto/response/ImageResponseDto.java
  src/main/java/com/ttubeog/domain/image/presentation/ImageController.java
  src/main/java/com/ttubeog/domain/road/application/RoadService.java
  src/main/java/com/ttubeog/domain/road/dto/request/CreateRoadRequestDto.java
  src/main/java/com/ttubeog/domain/road/dto/response/RoadResponseDto.java
  src/main/java/com/ttubeog/domain/road/presentation/RoadController.java
  src/main/java/com/ttubeog/domain/spot/presentation/SpotController.java
Labels: 🚶‍♀️초은, 🔧 update

#74 [Feat] 내 장소 조회 페이징
  src/main/java/com/ttubeog/domain/member/application/MemberService.java
  src/main/java/com/ttubeog/domain/member/dto/response/MemberPlaceDto.java
  src/main/java/com/ttubeog/domain/member/presentation/MemberController.java
  src/main/java/com/ttubeog/domain/spot/domain/repository/SpotRepository.java
  src/main/java/com/ttubeog/domain/store/domain/repository/StoreRepository.java
Labels: 🚶‍♀️아린, ✨ feature

#83 [Feat] Store 삭제 시 삭제되는 엔티티 추가
  src/main/java/com/ttubeog/domain/road/domain/repository/RoadRepository.java
  src/main/java/com/ttubeog/domain/roadcoordinate/domain/repository/RoadCoordinateRepository.java
  src/main/java/com/ttubeog/domain/store/application/StoreService.java
  src/main/java/com/ttubeog/domain/store/exception/UnathorizedMemberException.java
Labels: 🚶‍♀️정민, ✨ feature
